package com.cloud.springcloud.ecommerce.order.dao;

import com.cloud.springcloud.ecommerce.order.entity.EcommerceOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface EcommerceOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    int insert(EcommerceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    int insertSelective(EcommerceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    EcommerceOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EcommerceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecommerce_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcommerceOrder record);

    List selectOrderByExportPeopleCode(Map map) ;
}